# Generated by Django 4.1.2 on 2022-10-22 22:27

import api.user.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_remove_user_created_remove_user_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='update',
            field=api.user.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
    ]
