# Generated by Django 4.1.2 on 2022-10-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0003_user_created_user_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
