# Generated by Django 4.1.2 on 2022-10-22 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0004_alter_user_created_alter_user_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='update',
        ),
    ]
