# Generated by Django 4.1.2 on 2022-10-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0005_remove_user_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='github',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
