# Generated by Django 4.1.2 on 2022-10-28 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0003_alter_commentmodel_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='actor',
        ),
        migrations.AddField(
            model_name='likemodel',
            name='comment',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapi.commentmodel'),
        ),
        migrations.AddField(
            model_name='likemodel',
            name='type',
            field=models.TextField(default='like', editable=False),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterModelTable(
            name='likemodel',
            table='likesInformation',
        ),
    ]
