# Generated by Django 3.1.6 on 2022-10-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentmodel',
            table='commentInformation',
        ),
        migrations.AlterModelTable(
            name='logininformationmodle',
            table='loginInformation',
        ),
        migrations.AlterModelTable(
            name='postmodel',
            table='postInformation',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
