# Generated by Django 4.1.2 on 2022-10-28 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0004_remove_likemodel_actor_likemodel_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likemodel',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backendapi.postmodel'),
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapi.commentmodel'),
        ),
    ]
