# Generated by Django 3.1.6 on 2022-11-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0005_likemodel_post_alter_likemodel_comment'),
        ('backendapi', '0004_followermodel_type'),
    ]

    operations = [
    ]
