# Generated by Django 4.1.2 on 2022-11-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0004_followermodel_type'),
        ('backendapi', '0005_likemodel_post_alter_likemodel_comment'),
    ]

    operations = [
    ]
