# Generated by Django 3.1.6 on 2022-11-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0008_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
