# Generated by Django 3.1.6 on 2022-11-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0009_delete_test'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='node',
            table='node',
        ),
    ]
