# Generated by Django 3.1.6 on 2022-11-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0010_auto_20221125_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Node',
        ),
    ]
