# Generated by Django 3.1.6 on 2022-11-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0012_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
