# Generated by Django 4.1.2 on 2022-11-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0013_node_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='host',
            field=models.CharField(blank=True, default='https://cmput404-backend.herokuapp.com/backendapi/', max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='url',
            field=models.CharField(default='https://cmput404-backend.herokuapp.com/backendapi/authors/<django.db.models.fields.UUIDField>', max_length=225),
        ),
    ]
