# Generated by Django 4.1.2 on 2022-11-30 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0015_alter_postmodel_origin_alter_postmodel_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='inbox', max_length=100)),
                ('object', models.JSONField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='InboxModel',
        ),
    ]
