# Generated by Django 4.1.2 on 2022-11-30 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0002_alter_postmodel_origin_alter_postmodel_source_and_more'),
        ('backendapi', '0016_inboxobject_delete_inboxmodel'),
    ]

    operations = [
    ]
