# Generated by Django 4.1.2 on 2022-11-30 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0017_merge_20221130_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likemodel',
            name='post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapi.postmodel'),
        ),
    ]
