# Generated by Django 4.1.2 on 2022-12-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0017_merge_20221130_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
