# Generated by Django 4.1.2 on 2022-12-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0018_postmodel_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxobject',
            name='author',
            field=models.CharField(default='', max_length=256),
        ),
    ]
