# Generated by Django 4.1.2 on 2022-12-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0018_alter_likemodel_post'),
        ('backendapi', '0020_alter_inboxobject_object'),
    ]

    operations = [
    ]
