# Generated by Django 4.1.2 on 2022-12-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0021_merge_20221201_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='comments',
            field=models.URLField(null=True),
        ),
    ]
