# Generated by Django 4.1.2 on 2022-12-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0022_alter_postmodel_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='url_id',
            field=models.URLField(blank=True),
        ),
    ]
