# Generated by Django 4.1.2 on 2022-12-03 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0023_commentmodel_url_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followermodel',
            name='followedAuthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followedAuthors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followermodel',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
