# Generated by Django 4.1.2 on 2022-12-04 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0024_alter_followermodel_followedauthor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxobject',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
