# Generated by Django 4.1.2 on 2022-12-04 02:48

import backendapi.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0025_alter_inboxobject_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboxobject',
            name='object',
        ),
        migrations.AddField(
            model_name='inboxobject',
            name='object',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=backendapi.models.default_list, null=True, size=None),
        ),
    ]
