# Generated by Django 4.1.2 on 2022-12-04 02:49

import backendapi.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0026_alter_inboxobject_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxobject',
            name='object',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=backendapi.models.default_list, null=True, size=None),
        ),
    ]
