# Generated by Django 4.1.2 on 2022-12-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0029_alter_inboxobject_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='url_id',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='type',
            field=models.CharField(default='comment', editable=False, max_length=300),
        ),
    ]
