# Generated by Django 4.1.2 on 2022-12-05 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0032_alter_inboxobject_object'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ['-published']},
        ),
    ]
