# Generated by Django 4.1.2 on 2022-12-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0033_alter_commentmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ['published']},
        ),
    ]
